### ISSUE TITLE
Couleurs non remises au standard

### ISSUE THREAD

**Issue by fredt34** [PixiBixi/nginx-ensite#1]
Très bon script, merci

MAIS

Les couleurs du terminal ne sont pas remises aux valeurs d'origine... et c'est atroce de se retrouver avec un terminal en rouge! Je pense qu'il est possible de pemettre les couleurs d'origine en fin de chaines?

(du coup j'ai hacké avec un `tput sgr0` avant chaque exit...)

**Comment by PixiBixi** [comment]
Plop, ça doit être bon maintenant ! ;) https://github.com/PixiBixi/nginx-ensite/commit/100703c921debb92da95c6260ee4f5c787950d50
